//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_BITMAP3                     160
#define IDB_HUSKY                       160
#define IDB_BITMAP4                     162
#define IDB_MAP                         162
#define IDB_BITMAP5                     163
#define IDB_BITMAP9                     169
#define IDB_BITMAP6                     170
#define IDB_LOGO                        170
#define IDB_BOARD                       171
#define IDB_BUY                         172
#define IDB_SIBAINU                     173
#define IDB_BITMAP7                     174
#define IDB_CHOICE                      174
#define IDB_BAD                         175
#define IDB_BITMAP8                     176
#define IDB_FLEA                        176
#define IDB_HELPBACK                    180
#define IDB_PASSPAY                     183
#define IDB_FIRE                        184
#define IDB_HOTDOG                      185
#define IDB_HOUSE                       186
#define IDB_GOOD                        187
#define IDB_BITMAP10                    188
#define IDB_VET                         188
#define IDB_b1                          190
#define IDB_B1                          190
#define IDB_B2                          191
#define IDB_BITMAP11                    192
#define IDB_B3                          192
#define IDB_SMALLMAP                    193
#define IDB_SMALLP1                     194
#define IDB_BITMAP12                    195
#define IDB_SMALLP2                     195
#define IDB_HH                          196
#define IDB_BITMAP14                    197
#define IDB_SH                          197
#define IDB_BITMAP13                    199
#define IDB_OVER                        199
#define IDB_BITMAP15                    200
#define IDB_BUILD                       200
#define IDB_PNG1                        201
#define IDB_C1                          202
#define IDB_C2                          203
#define IDB_C3                          204
#define IDB_C4                          205
#define IDB_BITMAP18                    219
#define IDB_C5                          220
#define IDB_C6                          221
#define IDB_C7                          222
#define IDB_C8                          223
#define IDB_C9                          224
#define IDB_C10                         225
#define IDB_BITMAP23                    226
#define IDB_C11                         226
#define IDB_PNG2                        227
#define IDB_PNG3                        228
#define IDB_PNG4                        229
#define IDB_H1                          230
#define IDB_H2                          231
#define IDB_BITMAP19                    232
#define IDB_H3                          232
#define IDB_SMALLHUSKYHEAD              233
#define IDB_SMALLSHIBAHEAD              234
#define IDB_SMALLHOUSE1                 235
#define IDB_SMALLHOUSE2                 236
#define IDB_BITMAP16                    237
#define IDB_SMALLHOUSE3                 237
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        238
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
